
url: "https://viktorsapozhok.github.io/docker-postgres-influxdb-grafana/"
title: docker-postgres-influxdb-grafana
author: viktorsapozhok
description: Building animated maps with Grafana
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
